// NDI SDK FFI layer.
// These modules provide safe Rust wrappers around the NDI C SDK.
//
// The NDI SDK is proprietary and must be installed separately.
// Real FFI bindings would be auto-generated by bindgen from Processing.NDI.Lib.h.
//
// For now, these modules contain stub implementations that log warnings
// and return sensible defaults. To enable real NDI support:
// 1. Install the NDI SDK
// 2. Set NDI_SDK_DIR environment variable
// 3. Enable the `ndi` feature flag in Cargo.toml
// 4. Uncomment bindgen in build.rs

pub mod finder;
pub mod ptz;
pub mod receiver;
